### ISSUE TITLE
DIP: Solution Design [DMP]

### ISSUE THREAD

**Issue by saingersoll** [hmchilders/GaiaFuture#15]

**Comment by Sujan-Bhattarai12** [comment]
Can someone explain what I am doing in this solutions design part ? am I writing the unwritten ? or am I just editing the full solution Design for the final version.

**Comment by hmchilders** [comment]
Hi Sujan, you can see in the title of this issue that it says "Solution Design [DMP]" the [DMP] stands for Data Management Plan. You will be writing the Data Management Plan of the Solution Design Section (according to the Bren Capstone guidelines). If you need more guidance on this, I highly recommend reaching out to Carmen and she will be able to work with you on the specifics! There's also a tentative milestones document in the google drive that has the specifics of who will write each section

**Comment by Sujan-Bhattarai12** [comment]
thanks, Heather !



Regards
Sujan Bhattarai
