### ISSUE TITLE
create a shared utils library

### ISSUE THREAD

**Issue by djk2120** [hmchilders/GaiaFuture#3]
create a file called utils.py in the same directory that you'll be using for your jupyter notebooks.

here's some code to include in that file to get started. this function will get you 30 processors for parallel computing on casper. this is useful when you're looking at larger datasets. you only have to run this function once at the beginning of each coding session!

````
from dask_jobqueue import PBSCluster
from dask.distributed import Client
def get_cluster(account,cores=30):    
    """Spin up a dask cluster.

    Keyword arguments:
    account -- your account number, e.g. 'UCSB0021'
    cores -- the number of processors requested

    Returns:
    client -- can be useful to inspect client.cluster or run client.close()
    """

    cluster = PBSCluster(
    cores=1, # The number of cores you want
    memory='10GB', # Amount of memory
    processes=1, # How many processes
    queue='casper', # The type of queue to utilize (/glade/u/apps/dav/opt/usr/bin/execcasper)
    local_directory='$TMPDIR', # Use your local directory
    resource_spec='select=1:ncpus=1:mem=10GB', # Specify resources
    account=account, # Input your project ID here
    walltime='02:00:00', # Amount of wall time
    )

    # Scale up
    cluster.scale(cores)
    
    # Setup your client
    client = Client(cluster)

    return client
````

in your jupyter notebook you would run
`from utils import *`
to have access to all the functions in utils.py

**Comment by djk2120** [comment]
also useful:
````
def fix_time(ds):
    '''fix CESM monthly time-parsing bug'''
    yr0=str(ds['time.year'][0].values)
    ds['time']=xr.cftime_range(yr0,periods=len(ds.time),freq='MS',calendar='noleap')
    return ds
````

**Comment by djk2120** [comment]
it looks like dask_jobqueue may not be available in the meds-py environment, so you should also copy that environment.yml file we used into your github, and then edit it to include dask_jobqueue and then update your environments 

on the command line:
```
conda activate meds-py
conda env update --file environment.yml
```

**Comment by hmchilders** [comment]
copy /glade/u/home/djk2120/environment.yml into github

**Comment by hmchilders** [comment]
@saingersoll @Sujan-Bhattarai12 
need to update the environment, I recommend requesting 40GB from casper. solving the environment took ~ 2hours. set the wall time to 5hrs when updating.
