### ISSUE TITLE
make a diagram / outline of the 'barebones' workflow

### ISSUE THREAD

**Issue by djk2120** [hmchilders/GaiaFuture#4]
we discussed a barebones workflow today consisting of four functions chained together. you should diagram that workflow, and work towards identifying what would be the inputs and outputs of each function

**Comment by hmchilders** [comment]
https://docs.google.com/presentation/d/1AIj-Uf_lXPcVl93jjzzOlNLOykFYiGqscrh2HyLsp3U/edit?usp=sharing
